dependencies:
- name: aspnet-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.17
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: fish-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.40
- name: fish-webapps
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.48
